### ISSUE TITLE
Unable to save MITRE ATT&CK App for Splunk - In ital Setup 'Use Enterprise Security App' does not save

### ISSUE THREAD

**Issue by bmorri13** [seynur/DA-ESS-MitreContent#14]
Unable to save MITRE ATT&CK App for Splunk - In ital Setup 'Use Enterprise Security App' does not save:

Within the setup page, when trying to save the mitre_rules to utlizes the ES notables, I hit save and afterwards I refresh the page and the settings do not persist which causes the ES notable rules not to import correctly into the Compliance table.

https://github.com/seynur/DA-ESS-MitreContent/blob/master/default/macros.conf#L21-L35

**Comment by selimseynur** [comment]
Hello, 
Thanks for using the app.  Setup page has been tested with upgrade and new installs.  Perhaps we missed a step.  Can you share the environment details with us so that we can try to reproduce? Following information would be a good starting point.
- Splunk & ES app version information.
- Upgrade or new/fresh install?
- Any steps to reproduce the problem (e.g. setup page and hit save?)

As you've probably noticed, setup page is for convenience and it simply updates the macros.conf file.  If you'd like to skip it you can also simply edit the macros.conf file (comment out or enable) for it to work as a workaround for now.

**Comment by selimseynur** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue.

Thank you.
