### ISSUE TITLE
The lookup table 'mitre_api_rule_technique_lookup' requires a .csv or KV store lookup definition.

### ISSUE THREAD

**Issue by amyers1616** [seynur/DA-ESS-MitreContent#17]
Fresh install on Splunk Enterprise 8.1 here. I'm not using an API (yet) and not using Enterprise Security App either (box unchecked). When going to generate the lookup tables, the _MITRE ATT&CK All Rules and Techniques Lookup_ throws the error _The lookup table 'mitre_api_rule_technique_lookup' requires a .csv or KV store lookup definition._ 
Any thoughts on how to start to troubleshoot?
Thanks,
Aaron

![image](https://user-images.githubusercontent.com/45566311/103414478-309b1680-4b4c-11eb-913a-e6fdc755139b.png)

**Comment by selimseynur** [comment]
Thank you for using the app.  I was able to reproduce this error; the search tries to reach out to the missing CSV file and this will be fixed in the next minor version, probably this week :)
Meanwhile, as a workaround, you can simply create the lookup file either from search (within app context) or from the console.

| outputlookup mitre_api_rule_technique_lookup.csv
![image](https://user-images.githubusercontent.com/8026309/103454240-48a49e80-4ce2-11eb-91d6-646014e7f820.png)

OR

touch $SPLUNK_HOME/etc/apps/DA-ESS-MitreContent/lookups/mitre_api_rule_technique_lookup.csv

Best regards,
Selim

**Comment by amyers1616** [comment]
Awesome, that worked. Thanks!
